### ISSUE TITLE
Some advice.

### ISSUE THREAD

**Issue by ryantheleach** [DeleteThisAcount/DeleteThisAcount.github.io#5]
The typo in your web username, combined with the sentence "DeleteThisAcount" makes you appear to be a github troll at first glance, and unprofessional at a deeper one due to the typo.

I'd seriously consider changing it, if you plan on using github professionally for job hunting in the future.

Take this from someone whose github username is ryantheleach because their lastname is leach, and the misunderstandings that has created on various sites around the internet :-(.

**Comment by DeleteThisAcount** [comment]
ok thanks lol
